### ISSUE TITLE
Dataflöde: vilken data ska programmet ta emot respektive skicka ut?

### ISSUE THREAD

**Issue by xlsson** [freddyph/pattern-bikeprogram#1]
Dataflöde var lite den centrala punkten på dagens möte. Vilken data ska cykelns program ta emot, och vilken data ska den skicka? Så här tolkade jag vår diskussion, i extremt grova drag.

- Cykelns program tar emot input i form av riktning (north, south, east eller west), hastighet (d.v.s. hur långt cykeln ska förflyttas i den givna riktningen) samt avslut av resa.
- Inputen levereras antingen manuellt (via en enkel input-prompt i Python-programmet) eller via vår simulering (som skickar framslumpad input till cykelns program).
- Efter varje input räknar cykelns program ut de nya koordinaterna, batterinivå och sammanlagd körsträcka (eventuellt ytterligare data?) och skickar relevant data till servern.

Automatiseringen av riktning och hastighet hamnar alltså i simuleringen = utanför cykelns program.

Är detta rätt utgångspunkt?

**Comment by freddyph** [comment]
Åtgärdat!
