### ISSUE TITLE
Tankar om serveranrop för cykelns position

### ISSUE THREAD

**Issue by xlsson** [freddyph/pattern-bikeprogram#2]
Behöver man hämta cykelns position vid varje rörelse? Kan positionen istället bestämmas internt inne i programmet, baserat på ursprungsposition och tidigare rörelser? Det vore kanske ett sätt att begränsa belastningen på servern.

Det borde inte finnas någon risk för att det blir fel, tänker jag: under en pågående resa kan en admin inte begära hämtning av en cykel, så den kund som för tillfället kör cykeln är den enda som kan ändra cykelns position.

**Comment by freddyph** [comment]
Åtgärdat!
